### PR TITLE
Cu apybj0 front end tests joe mindo

### PR DESCRIPTION
**Pull request by Mindo-Joseph**
### What does this PR do?
- **Creates the frontend tests**

### How can this be manually tested?
- Install [Cypress](https://docs.cypress.io/guides/getting-started/installing-cypress.html#System-requirements)
- Start your server
- Type the following command ```node_modules/.bin/cypress open```
- You should see a screen such as 
Screenshot from 2020-12-10 02-59-21
- Click on the files named, ```home_page_spec.js write_page_spec.js and speak_page_spec.js```
- For each file,
Screenshot from 2020-12-10 03-02-44
 a window showing the results should pop up

### CODE REVIEW

**Comment by martinoywa** [comment]
Task linked: [CU-apybj0 Front-end tests](https://app.clickup.com/t/apybj0)

**Comment by martinoywa** [comment]
Perfect! Who’s reviewing this PR?

**Review by martinoywa — COMMENTED** [review]
Everything looks okay for me, although we'll need to make some changes during integration.
Is there a way these tests can be automated using workflows?

**Comment by Mindo-Joseph** [comment]
Probably! Lemme look into how I can do that

**Comment by martinoywa** [comment]
Awesome!

**Review by KelynPNjeri — APPROVED** [review]
Everything looks good on my end.

**Review by KelynPNjeri — APPROVED** [review]
Everything looks great on my end. Good job. Go ahead and merge.

**Pull request merged**
