### PR TITLE
Speech to text numbers to words

### PR DESCRIPTION
**Pull request by martinoywa**
Update STT module test to convert numbers to words.

### CODE REVIEW

**Comment by martinoywa** [comment]
Task linked: [CU-apyep5 Speech to text module](https://app.clickup.com/t/apyep5)

**Review by KelynPNjeri — COMMENTED** [review]
Hey, I only see you updated the test file. Did you do the same for the functionality.

**Comment by martinoywa** [comment]
It just hit me that I updated the wrong thing. Thanks for that!

**Review by KelynPNjeri — APPROVED** [review]
Great job. Just saw the rest of the code. Feel free to merge.

**Comment by martinoywa** [comment]
Perfect!

**Pull request merged**
