### PR TITLE
Cu apyem5 image recognition module martin oywa

### PR DESCRIPTION
**Pull request by martinoywa**

### CODE REVIEW

**Comment by martinoywa** [comment]
Task linked: [CU-apyem5 Image recognition module](https://app.clickup.com/t/apyem5)

**Review by Mindo-Joseph — CHANGES_REQUESTED** [review]
Great job :clap: , I would like it if you could add a description of how to run the project in the README.md file so that someone knows how to get started with the project

**Comment by martinoywa** [comment]
Perfect! I'm not sure how exactly that'll help at this point in the project
considering no branches have been merged. Or should I just have it in the
the backend README.md?

**Comment by martinoywa** [comment]
I can do that on the app runner branch, it's separate from this one.

**Comment by Mindo-Joseph** [comment]
I was thinking just a small description on how to get the project up and running

**Comment by martinoywa** [comment]
Perfect! That's fine. Will have it ready by tomorrow.

**Comment by Mindo-Joseph** [comment]
Great :clinking_glasses:  @martinoywa

**Comment by martinoywa** [comment]
Task linked: [CU-apye03 Application Runner](https://app.clickup.com/t/apye03)

**Comment by martinoywa** [comment]
All requested changes have been made on the `CU-apye03_Application-Runner_Martin-Oywa` branch.

**Review by KelynPNjeri — APPROVED** [review]
Good Job.

**Review by Mindo-Joseph — APPROVED** [review]
Great :rocket: :100:

**Pull request merged**
