### PR TITLE
Add initial application runner

### PR DESCRIPTION
**Pull request by martinoywa**
https://app.clickup.com/4522322/v/dc/4a0aj-113/4a0aj-29

### CODE REVIEW

**Comment by martinoywa** [comment]
Task linked: [CU-apye03 Application Runner](https://app.clickup.com/t/apye03)

**Comment by KelynPNjeri** [comment]
It looks alright to me. Mergeable.

**Comment by martinoywa** [comment]
> It looks alright to me. Mergeable.

Perfect, you should mark as reviewed then. I can't do it on my side.
Thanks.

**Review by KelynPNjeri — APPROVED** [review]
Everything looks good.

**Comment by martinoywa** [comment]
Task linked: [CU-apye03 Application Runner](https://app.clickup.com/t/apye03)

**Pull request merged**
